name: Build and Sign Android Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: |
         mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.jks

      - name: Build Android Release Bundle (AAB)
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
        working-directory: android  
          chmod +x gradlew
          ./gradlew bundleRelease
          
      - name: Upload Signed AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: android/app/build/outputs/bundle/release/app-release.aab
